http:
  listener:
    host: "localhost"
    port: "9081"
    path: "/travelOnTipCall/{serviceType}"
    
db:
  mysql:
    host: "localhost"
    port: "3306"
    username: "root"
    password: "Rajpoot@2514"
    databaseName: "MulesoftTraining"